### ISSUE TITLE
Application::find() must be of the type string, array given

### ISSUE THREAD

**Issue by psaulus13** [RikudouSage/RikudouCronBundle#3]
When I'm trying to run my cron jobs by _YAML_ file I got error like that:

```
[2023-09-22T12:36:00.529967+00:00] app.INFO: [CRON] Executing command imagesClean [] []
[2023-09-22T12:36:00.530003+00:00] app.ERROR: [CRON] Execution of command imagesClean failed [] []
[2023-09-22T12:36:00.530069+00:00] app.ERROR: [CRON] Argument 1 passed to Symfony\Bundle\FrameworkBundle\Console\Application::find() must be of the type string, array given, called in /var/www/html/vendor/rikudou/cron-bundle/Command/RunCronJobsCommand.php on line 84 [] []
[2023-09-22T12:36:00.530127+00:00] app.ERROR: [CRON] #0 /var/www/html/vendor/rikudou/cron-bundle/Command/RunCronJobsCommand.php(84): Symfony\Bundle\FrameworkBundle\Console\Application->find(Array) #1 /var/www/html/vendor/symfony/console/Command/Command.php(298): Rikudou\CronBundle\Command\RunCronJobsCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #2 /var/www/html/vendor/symfony/console/Application.php(1058): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #3 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(96): Symfony\Component\Console\Application->doRunCommand(Object(Rikudou\CronBundle\Command\RunCronJobsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #4 /var/www/html/vendor/symfony/console/Application.php(301): Symfony\Bundle\FrameworkBundle\Console\Application->doRunCommand(Object(Rikudou\CronBundle\Command\RunCronJobsCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #5 /var/www/html/vendor/symfony/framework-bundle/Console/Application.php(82): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #6 /var/www/html/vendor/symfony/console/Application.php(171): Symfony\Bundle\FrameworkBundle\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput)) #7 /var/www/html/bin/console(39): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput)) #8 {main} [] []
[2023-09-22T12:36:00.531052+00:00] console.DEBUG: Command "cron:run" exited with code "1" {"command":"cron:run","code":1} []
```

This is how my _rikudou_cron.yml_ file looks like:
```
rikudou_cron:
    imagesClean:
      command: images:clean --limit 2500 > /root/imageclean.log
      cron_expression: "* * * * *"
```

**Comment by psaulus13** [comment]
In the _RunCronJobsCommand_ in line 84 there should be probably something like this: `$command = $this->getApplication()->find($command['command']);` or, of course, something more in OOP-ish style. ;) @RikudouSage

**Comment by psaulus13** [comment]
And more over... I'm pretty sure that then, it doesn't accept arguments for the command. For example when I have something like this: `equations:recalculate SOMEARG` I got `ommand "equations:recalculate SOMEARG" is not defined.`.

**Comment by RikudouSage** [comment]
Which version are you using? The line 84 doesn't contain anything related to this. But your problem most likely lies with the inability to pass arguments, I'll fix that.

**Comment by psaulus13** [comment]
Yea, I see that you fixed it in the newest version. But it is still in use in version v1.0.0 which I need to use because of my PHP version. :) Look at this line in the mentioned file in this version please.

**Comment by RikudouSage** [comment]
Well, the options are added, but I'm afraid that won't help you if you're stuck at 1.0.0.

**Comment by psaulus13** [comment]
No, it won't the bug is still on this version. :( But this feature will be useful for others and maybe me later. :)

**Comment by RikudouSage** [comment]
You might try looking at something like this: https://github.com/phabelio/phabel

Though I have no idea how well maintained it is.
